spring:
  application:
    name: ServiceConsumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
        username: nacos
        password: nacos

server:
  port: 8003

feign:
  client:
    config:
      default:
        # 日志级别
        loggerLevel: full
        # 从连接建立时开始应用，在返回响应时间过长时触发。
        readTimeout: 5000
        # 指的是建立连接后从服务器读取到可用资源所用的时间
        connectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.wht.service.FeignService: debug