
spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
        username: nacos
        password: nacos

server:
  port: 8001





